# $HOME/.config/alacritty/alacritty.toml
[window]

opacity = 0.8
blur = true

padding.x = 2
padding.y = 2

decorations = "Full"

#decorations_theme_variant = "Light" # "Dark"

[font]
normal.family = "JetbrainsMono Nerd Font Mono"
bold.family = "JetBrainsMono Nerd Font Mono"
italic.family = "JetBrainsMono Nerd Font Mono"
bold_italic.family = "JetBrainsMono Nerd Font Mono"

size = 17.0

[colors]
cursor = { text = "CellBackground", cursor = "#ff0000" }
transparent_background_colors = true

[cursor]
style = {shape= "Beam",blinking = "Off"}
