# $HOME/.config/alacritty/alacritty.toml
[window]

opacity = 0.9

padding.x = 10
padding.y = 10

decorations = "Full"
#decorations_theme_variant = "Light" # "Dark"

[font]

normal.family = "Monaspace Neon"
bold.family = "Monaspace Neon"
italic.family = "Monaspace Neon"
bold_italic.family = "Monaspace Neon"

size = 17.0


