source $HOME/.config/aliases
source $HOME/.config/variables


autoload -Uz compinit
typeset -i updated_at=$(date +'%j' -r ~/.zcompdump 2>/dev/null || stat -f '%Sm' -t '%j' ~/.zcompdump 2>/dev/null)
if [ $(date +'%j') != $updated_at ]; then
  compinit -i
else
  compinit -C -i
fi

zmodload -i zsh/complist

HISTFILE=$HOME/.config/zsh/.zsh_history
HISTSIZE=100000
SAVEHIST=$HISTSIZE


setopt hist_ignore_all_dups # remove older duplicate entries from history
setopt hist_reduce_blanks # remove superfluous blanks from history items
setopt inc_append_history # save history entries as soon as they are entered
#setopt share_history # share history between different instances of the shell


#setopt correct_all # autocorrect commands

setopt auto_list # automatically list choices on ambiguous completion
setopt auto_menu # automatically use menu completion
setopt always_to_end # move cursor to end if word had one match


zstyle ':completion:*' menu select # select completions with arrow keys
zstyle ':completion:*' group-name '' # group results by category
zstyle ':completion:::::' completer _expand _complete _ignored _approximate # enable approximate matches for completion


bindkey '^[[3~' delete-char
bindkey '^[3;5~' delete-char


autoload -Uz vcs_info

function check_last_exit_code() {
  local LAST_EXIT_CODE=$?
  if [[ $LAST_EXIT_CODE -ne 0 ]]; then
    local EXIT_CODE_PROMPT=' '
    EXIT_CODE_PROMPT+="%F{1}✖"
    EXIT_CODE_PROMPT+="%F{9}$LAST_EXIT_CODE"
    EXIT_CODE_PROMPT+="%F{1}✖%f"
    echo "$EXIT_CODE_PROMPT"
  fi
}

preexec() {
#    cmd_start=$(date +%s%N)
}

precmd() {
  vcs_info
#  local cmd_end=$(date +%s%N)
#  local elapsed_time=$((cmd_end-cmd_start))
#  elapsed=$(printf "%.2f" $((elapsed_time*.000000001)))
}

# Format the vcs_info_msg_0_ variable
zstyle ':vcs_info:git:*' formats ' %b'

# Set up the prompt (with git branch name)
setopt PROMPT_SUBST

RPROMPT='$(check_last_exit_code)'

PROMPT='%F{10}%m:%F{12}%~%f%F{1}${vcs_info_msg_0_}%f$'


if [ -S "$SSH_AUTH_SOCK" ]; then
    ln -sf $SSH_AUTH_SOCK ~/.ssh/ssh_auth_sock
fi



if [[ ! -e ~/.ssh/ssh_auth_sock ]]; then
    eval `ssh-agent -s` &> /dev/null
    trap 'test -n "$SSH_AGENT_PID" && eval `/usr/bin/ssh-agent -k`' 0
    ln -sf $SSH_AUTH_SOCK ~/.ssh/ssh_auth_sock
fi


#export SSH_AUTH_SOCK="~/.ssh/ssh_auth_sock"

printf "\033]0;${HOST}\007"
